apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: kovalov-site:v1
        imagePullPolicy: IfNotPresent
        name: kovalov-site
        resources: {}
status: {}
